# list out the driver program source 

PROGS = stepper-test.c
COMMON_SRC := stepper.c stepper-int.c

RUN = 1

LIB_POST := $(CS240LX_2024_PATH)/lib/libgcc.a
LIBS += $(LIB_POST)
include $(CS240LX_2024_PATH)/libpi/mk/Makefile.template-fixed
