# list out the driver program source 
PROGS = test-gen.c

# pick one of your attachment points (first or last) consistently.
BOOTLOADER = my-install --last

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS240LX_2024_PATH)/libpi/mk/Makefile.template-fixed

