# list out the driver program source 
PROGS = scope.c

BOOTLOADER = my-install --first

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS240LX_2024_PATH)/libpi/mk/Makefile.template-fixed

