# list out the driver program source 
PROGS = 0-circle-test.c

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

LIB_POST := $(CS240LX_2024_PATH)/lib/libgcc.a
LIBS += $(LIB_POST)

DEPS = ./Makefile
include $(CS240LX_2024_PATH)/libpi/mk/Makefile.template-fixed
