PROGS = int-compile.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

include ../../../../libpi/mk/Makefile.template-fixed

